In [23]:
import pandas as pd
import numpy as np
from numpy import mat, zeros, nonzero, mean, inf,sqrt, sum, power, random

data = pd.read_csv('test_data.csv')
data=np.array(data)
data

array([[-3.453687,  3.424321],
       [ 4.838138, -1.151539],
       [-5.379713, -3.362104],
       [ 0.972564,  2.924086],
       [-3.567919,  1.531611],
       [ 0.450614, -3.302219],
       [-3.487105, -1.724432],
       [ 2.668759,  1.594842],
       [-3.156485,  3.191137],
       [ 3.165506, -3.999838],
       [-2.786837, -3.099354],
       [ 4.208187,  2.984927],
       [-2.123337,  2.943366],
       [ 0.704199, -0.479481],
       [-0.39237 , -3.963704],
       [ 2.831667,  1.574018],
       [-0.790153,  3.343144],
       [ 2.943496, -3.357075],
       [-3.195883, -2.283926],
       [ 2.336445,  2.875106],
       [-1.786345,  2.554248],
       [ 2.190101, -1.90602 ],
       [-3.403367, -2.778288],
       [ 1.778124,  3.880832],
       [-1.688346,  2.230267],
       [ 2.592976, -2.054368],
       [-4.007257, -3.207066],
       [ 2.257734,  3.387564],
       [-2.679011,  0.785119],
       [ 0.939512, -4.023563],
       [-3.674424, -2.261084],
       [ 2.046259,  2.735279],
       [

In [24]:
#计算距离
def distEuclidean(vecA, vecB):
    return sqrt(sum(power(vecA - vecB, 2)))

#计算中心点
def randCent(data, k):
    dim = data.shape[1]
    
    # 创建用于存储质心矩阵的空变量
    centroids = mat(zeros((k, dim)))
    
    for j in range(dim):

        minJ = min(data[:,j]) 
        rangeJ = float(max(data[:,j]) - minJ)
        
        # 某特征的随机k个值
        centroids[:, j] = mat(minJ + rangeJ * random.rand(k, 1))
    return centroids


def kMeans(data, k):
    m = data.shape[0]
    clusterAssment = mat(zeros((m, 2))) # 创建存储簇分配结果的矩阵
    centroids = randCent(data, k) # 簇中心矩阵
    clusterChanged = True # 簇分配结果改变标志
    while clusterChanged:
        clusterChanged = False
        
        # 遍历每个数据点，计算其与各簇中心的距离，以最近簇作为分配结果
        for i in range(m):
            minDist = inf
            minIndex = -1
            for j in range(k):
                
                # 计算数据点i与簇中心j的欧式距离
                distJI = distEuclidean(centroids[j, :],data[i, :])
                
                # 得到最小距离的簇中心minIndex及对应最小距离minDist
                if distJI < minDist:
                    minDist = distJI
                    minIndex = j
            
            # 比较上一轮簇分配结果与当前促分配结果是否一致
            if clusterAssment[i, 0] != minIndex: 
                clusterChanged = True
            
            # 更新样本簇分配结果
            clusterAssment[i, :] = minIndex, minDist**2
        
        #重新计算各簇的中心
        for cent in range(k):
            
            # 获得簇内数据矩阵
            ptsInClust = data[nonzero(clusterAssment[:, 0]==cent)[0]] 
            centroids[cent, :] = mean(ptsInClust, axis=0)           
    return centroids, clusterAssment

In [25]:
np.random.seed(6)
centroids, clusterAssment = kMeans(data, 4)
print (centroids)
print (clusterAssment)

[[ 2.65077367 -2.79019029]
 [-2.46154315  2.78737555]
 [ 2.67745332  3.04676142]
 [-3.53973889 -2.89384326]]
[[ 1.          1.39004893]
 [ 0.          7.46974076]
 [ 3.          3.60477283]
 [ 2.          2.92169684]
 [ 1.          2.80101213]
 [ 0.          5.10287596]
 [ 3.          1.37029303]
 [ 2.          2.1081456 ]
 [ 1.          0.64596748]
 [ 0.          1.72819697]
 [ 3.          0.60909593]
 [ 2.          2.34696911]
 [ 1.          0.13871642]
 [ 0.          9.12853034]
 [ 0.         10.63785781]
 [ 2.          2.19275504]
 [ 1.          3.1024236 ]
 [ 0.          0.40704464]
 [ 3.          0.49023594]
 [ 2.          0.14575226]
 [ 1.          0.510241  ]
 [ 0.          0.9939764 ]
 [ 3.          0.03195031]
 [ 2.          1.50446695]
 [ 1.          0.90820377]
 [ 0.          0.54477501]
 [ 3.          0.31668166]
 [ 2.          0.2923107 ]
 [ 1.          4.05632356]
 [ 0.          4.44962474]
 [ 3.          0.41852436]
 [ 2.          0.49542756]
 [ 1.          1.5441411 ]
